mappings:
  - device: でんき
    action: あかるく
    deviceID: 01-202501041941-60635928
    commands:
      # 「いちばんあかるく」みたいなワードは需要があればやる
      # とりあえず一発で最大輝度にする
      - command: brightnessUp
        parameter: default
        commandType: command
      - command: brightnessUp
        parameter: default
        commandType: command
      - command: brightnessUp
        parameter: default
        commandType: command
      - command: brightnessUp
        parameter: default
        commandType: command
  - device: でんき
    action: くらく
    deviceID: 01-202501041941-60635928
    commands:
      # 同上
      - command: brightnessDown
        parameter: default
        commandType: command
      - command: brightnessDown
        parameter: default
        commandType: command
      - command: brightnessDown
        parameter: default
        commandType: command
      - command: brightnessDown
        parameter: default
        commandType: command
  - device: でんき
    action: けす
    deviceID: 01-202501041941-60635928
    commands:
      - command: turnOff
        parameter: default
        commandType: command
  - device: でんき
    action: つける
    deviceID: 01-202501041941-60635928
    commands:
      - command: turnOn
        parameter: default
        commandType: command